/*
Enter your query here.
*/

    SELECT 
        MIN(CASE WHEN OCCUPATION = 'Doctor' THEN NAME END),
        MIN(CASE WHEN OCCUPATION = 'Professor' THEN NAME END),
        MIN(CASE WHEN OCCUPATION = 'Singer' THEN NAME END),
        MIN(CASE WHEN OCCUPATION = 'Actor' THEN NAME END)
    FROM(
        SELECT
        OCCUPATION,
        NAME,
        ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME ASC) AS VAR1
    FROM OCCUPATIONS) SUBQUERY
    GROUP BY VAR1
    ORDER BY VAR1