/*
Enter your query here.
*/

SELECT CONCAT(CONCAT(CONCAT(NAME, '('), LEFT(UPPER(OCCUPATION), 1)), ')')
FROM OCCUPATIONS
ORDER BY NAME ASC;

SELECT  'There are a total of', COUNT(*) AS TOTAL, CONCAT(LOWER(OCCUPATION), "s.")
FROM OCCUPATIONS
group by OCCUPATION
ORDER BY TOTAL ASC;